spring:
  # Spring Data Source (JPA)
  datasource:
    url: jdbc:postgresql://localhost:5432/sandbox
    username: postgres
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
  graphql:
    graphiql:
      enabled: true
rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest
#    main:
#      allow-bean-definition-overriding: true

management:
  endpoints:
    web:
      exposure:
        include: mappings

springdoc:
  api-docs:
    path: /v1/docs

server:
  port: 8095
