server:
  port: 8095
logging:
  level:
    root: debug
name:
  firstname: Alfonsus
  lastname : Jacub
  token: RdarFKqJVkP7n9gD4HOtdXhkSrx7xvtb
appvar:
  token:
    signingkey: RdarFKqJVkP7n9gD4HOtdXhkSrx7xvtb

spring:
  datasource:
#    driver-class-name : org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bootcamp_db
    username: postgres
    password: password
    type: com.zaxxer.hikari.HikariDataSource
  jpa:
    hibernate:
      ddl-auto:  update
    show-sql: true
    generate-ddl: true
  cloud:
    openfeign:
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
management:
  endpoints:
    web:
      exposure:
        include: "*"




